console.log("Angka 2");
console.log(2 / -0);
console.log("Angka 39");
console.log(39 / -0);
console.log("Angka 76");
console.log(76 / -0);
console.log("Angka 50");
console.log(50 / -0);
console.log("Angka 9");
console.log(9 / -0);
console.log("Angka 7");
console.log(7 / -0);
console.log("Angka 41");
console.log(41 / -0);
console.log("Angka 2");
console.log(2 / -0);
console.log("Angka 24");
console.log(24 / -0);
console.log("Angka 1");
console.log(1 / -0);
console.log("Angka 16");
console.log(16 / -0);
